/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import phamacy.Phamacy;

/**
 *
 * @author Prabhash
 */
public class Login extends javax.swing.JFrame {
   int attempt=0;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtxtusername = new javax.swing.JTextField();
        jpassword = new javax.swing.JPasswordField();
        jButtonLogin = new javax.swing.JButton();
        jbuttonexit = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jButtonDoctor = new javax.swing.JButton();
        jButtonDoctor1 = new javax.swing.JButton();
        jButtonDoctor2 = new javax.swing.JButton();
        jButtonDoctor3 = new javax.swing.JButton();
        jButtonDoctor4 = new javax.swing.JButton();
        jButtonDoctor5 = new javax.swing.JButton();
        jButtonDoctor6 = new javax.swing.JButton();
        jButtonDoctor7 = new javax.swing.JButton();
        jButtonDoctor8 = new javax.swing.JButton();
        jButtonDoctor9 = new javax.swing.JButton();
        jButtonDoctor10 = new javax.swing.JButton();
        jButtonDoctor11 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 51, 0), 3));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Password:    ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("User Name:");

        jtxtusername.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtusernameActionPerformed(evt);
            }
        });

        jpassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jpassword.setText("Password");

        jButtonLogin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonLogin.setText("Login");
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });

        jbuttonexit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbuttonexit.setText("Exit");
        jbuttonexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonexitActionPerformed(evt);
            }
        });

        jButtonCancel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jButtonLogin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                        .addComponent(jButtonCancel)
                        .addGap(71, 71, 71)
                        .addComponent(jbuttonexit)
                        .addGap(90, 90, 90))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtusername)
                            .addComponent(jpassword, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                        .addGap(100, 100, 100))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbuttonexit)
                    .addComponent(jButtonCancel)
                    .addComponent(jButtonLogin))
                .addGap(39, 39, 39))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 620, 310));

        jButtonDoctor.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonDoctor.setText("GPAppoinment");
        jButtonDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDoctorActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 310, -1));

        jButtonDoctor1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonDoctor1.setText("Doctor");
        getContentPane().add(jButtonDoctor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 310, -1));

        jButtonDoctor2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonDoctor2.setText("Pharmacy");
        jButtonDoctor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDoctor2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDoctor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 310, -1));

        jButtonDoctor3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonDoctor3.setText("Patient");
        getContentPane().add(jButtonDoctor3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 310, -1));

        jButtonDoctor4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonDoctor4.setText("Pharmacy Office");
        getContentPane().add(jButtonDoctor4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 310, -1));

        jButtonDoctor5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonDoctor5.setText("Payment");
        getContentPane().add(jButtonDoctor5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 310, -1));

        jButtonDoctor6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonDoctor6.setText("Pharmacist");
        getContentPane().add(jButtonDoctor6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 370, 220, -1));

        jButtonDoctor7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonDoctor7.setText("Surgery");
        getContentPane().add(jButtonDoctor7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 130, 220, -1));

        jButtonDoctor8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonDoctor8.setText("Hospital");
        getContentPane().add(jButtonDoctor8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 190, 220, -1));

        jButtonDoctor9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonDoctor9.setText("Specialist");
        getContentPane().add(jButtonDoctor9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 250, 220, -1));

        jButtonDoctor10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonDoctor10.setText("Help");
        getContentPane().add(jButtonDoctor10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 440, 220, -1));

        jButtonDoctor11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonDoctor11.setText("Consultant");
        getContentPane().add(jButtonDoctor11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 310, 220, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153), 2));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setText("PHARMACY MANAGEMENT SYSTEM");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel2)
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 1050, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtusernameActionPerformed
  
   private JFrame frame;
    private void jbuttonexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonexitActionPerformed
      
    frame=new JFrame ("Exit");
    if(JOptionPane.showConfirmDialog(frame,"Confirm if you want to exit","Pharmacy Management System",
            JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
    System.exit(0);
    }
        
      
     
    }//GEN-LAST:event_jbuttonexitActionPerformed

    private void jButtonDoctor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDoctor2ActionPerformed
       Phamacy myPharmacy = new Phamacy();
       myPharmacy.setVisible(true);
       
       
    }//GEN-LAST:event_jButtonDoctor2ActionPerformed

    private void jButtonDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDoctorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDoctorActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
      jButtonDoctor.setEnabled(false);
      jButtonDoctor1.setEnabled(false);
      jButtonDoctor2.setEnabled(false);
      jButtonDoctor3.setEnabled(false);
      jButtonDoctor4.setEnabled(false);
      jButtonDoctor5.setEnabled(false);
      jButtonDoctor6.setEnabled(false);
      jButtonDoctor7.setEnabled(false);
      jButtonDoctor8.setEnabled(false);
      jButtonDoctor9.setEnabled(false);
      jButtonDoctor10.setEnabled(false);
      jButtonDoctor11.setEnabled(false);
      
           
      
    }//GEN-LAST:event_formWindowActivated

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
    jtxtusername.setText("");
    jpassword.setText("");
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
       String Username = jtxtusername.getText();
       String Password = jpassword.getText();
       
        if (Username.contains("one")&&(Password.contains("one")))
        {
        jtxtusername.setText("");
        jpassword.setText("");
        
         jButtonDoctor.setEnabled(true);
      jButtonDoctor1.setEnabled(true);
      jButtonDoctor2.setEnabled(true);
      jButtonDoctor3.setEnabled(true);
      jButtonDoctor4.setEnabled(true);
      jButtonDoctor5.setEnabled(true);
      jButtonDoctor6.setEnabled(true);
      jButtonDoctor7.setEnabled(true);
      jButtonDoctor8.setEnabled(true);
      jButtonDoctor9.setEnabled(true);
      jButtonDoctor10.setEnabled(true);
      jButtonDoctor11.setEnabled(true);
        }
        else if( !(Username.contains("one")&&(Password.contains("one"))) )     
       
        {
        jButtonDoctor.setEnabled(false);
        jButtonDoctor1.setEnabled(false);
        jButtonDoctor2.setEnabled(false);
        jButtonDoctor3.setEnabled(false);
        jButtonDoctor4.setEnabled(false);
        jButtonDoctor5.setEnabled(false);
        jButtonDoctor6.setEnabled(false);
        jButtonDoctor7.setEnabled(false);
        jButtonDoctor8.setEnabled(false);
        jButtonDoctor9.setEnabled(false);
        jButtonDoctor10.setEnabled(false);
        jButtonDoctor11.setEnabled(false);
        
        attempt +=1;
        
        if (attempt==3)
        {
            System.exit(0);
        }
        }
    }//GEN-LAST:event_jButtonLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonDoctor;
    private javax.swing.JButton jButtonDoctor1;
    private javax.swing.JButton jButtonDoctor10;
    private javax.swing.JButton jButtonDoctor11;
    private javax.swing.JButton jButtonDoctor2;
    private javax.swing.JButton jButtonDoctor3;
    private javax.swing.JButton jButtonDoctor4;
    private javax.swing.JButton jButtonDoctor5;
    private javax.swing.JButton jButtonDoctor6;
    private javax.swing.JButton jButtonDoctor7;
    private javax.swing.JButton jButtonDoctor8;
    private javax.swing.JButton jButtonDoctor9;
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbuttonexit;
    private javax.swing.JPasswordField jpassword;
    private javax.swing.JTextField jtxtusername;
    // End of variables declaration//GEN-END:variables
}
